[2024-10-09T14:21:22.383+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-09T14:21:22.404+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_database.get_date_from_postgres manual__2024-10-09T14:21:19.685041+00:00 [queued]>
[2024-10-09T14:21:22.413+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_database.get_date_from_postgres manual__2024-10-09T14:21:19.685041+00:00 [queued]>
[2024-10-09T14:21:22.415+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-09T14:21:22.429+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_date_from_postgres> on 2024-10-09 14:21:19.685041+00:00
[2024-10-09T14:21:22.439+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=638) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-09T14:21:22.441+0000] {standard_task_runner.py:63} INFO - Started process 640 to run task
[2024-10-09T14:21:22.441+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_database', 'get_date_from_postgres', 'manual__2024-10-09T14:21:19.685041+00:00', '--job-id', '3877', '--raw', '--subdir', 'DAGS_FOLDER/update.py', '--cfg-path', '/tmp/tmp75ija99z']
[2024-10-09T14:21:22.443+0000] {standard_task_runner.py:91} INFO - Job 3877: Subtask get_date_from_postgres
[2024-10-09T14:21:22.492+0000] {task_command.py:426} INFO - Running <TaskInstance: update_database.get_date_from_postgres manual__2024-10-09T14:21:19.685041+00:00 [running]> on host 9ee81962cd27
[2024-10-09T14:21:22.584+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_database' AIRFLOW_CTX_TASK_ID='get_date_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T14:21:19.685041+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-09T14:21:19.685041+00:00'
[2024-10-09T14:21:22.585+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-09T14:21:22.595+0000] {base.py:84} INFO - Using connection ID 'football_scotland_connection' for task execution.
[2024-10-09T14:21:22.600+0000] {logging_mixin.py:188} INFO - 2024-05-19
[2024-10-09T14:21:22.601+0000] {python.py:237} INFO - Done. Returned value was: 2024-05-19
[2024-10-09T14:21:22.602+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-09T14:21:22.625+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=update_database, task_id=get_date_from_postgres, run_id=manual__2024-10-09T14:21:19.685041+00:00, execution_date=20241009T142119, start_date=20241009T142122, end_date=20241009T142122
[2024-10-09T14:21:22.657+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-09T14:21:22.678+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-09T14:21:22.680+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
