[2024-10-08T14:33:49.559+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-08T14:33:49.583+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_database.run_sofascore_scraper manual__2024-10-08T14:20:23.650666+00:00 [queued]>
[2024-10-08T14:33:49.591+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_database.run_sofascore_scraper manual__2024-10-08T14:20:23.650666+00:00 [queued]>
[2024-10-08T14:33:49.592+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-08T14:33:49.603+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_sofascore_scraper> on 2024-10-08 14:20:23.650666+00:00
[2024-10-08T14:33:49.609+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=209) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T14:33:49.611+0000] {standard_task_runner.py:63} INFO - Started process 211 to run task
[2024-10-08T14:33:49.611+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_database', 'run_sofascore_scraper', 'manual__2024-10-08T14:20:23.650666+00:00', '--job-id', '3839', '--raw', '--subdir', 'DAGS_FOLDER/update.py', '--cfg-path', '/tmp/tmpu1ug2rn3']
[2024-10-08T14:33:49.612+0000] {standard_task_runner.py:91} INFO - Job 3839: Subtask run_sofascore_scraper
[2024-10-08T14:33:49.650+0000] {task_command.py:426} INFO - Running <TaskInstance: update_database.run_sofascore_scraper manual__2024-10-08T14:20:23.650666+00:00 [running]> on host 1fee8bc549a8
[2024-10-08T14:33:49.735+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_database' AIRFLOW_CTX_TASK_ID='run_sofascore_scraper' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T14:20:23.650666+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T14:20:23.650666+00:00'
[2024-10-08T14:33:49.737+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-08T14:33:49.738+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-08T14:33:49.739+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -d --name sofascore_scraper_container -v C:/Users/efsta/Desktop/Kostas/Data/football_scotland/***/dags/sofascore_scraper_container/csv:/app/csv kostasmitalloulis/sofascoe_scraper_image_up:latest ']
[2024-10-08T14:33:49.753+0000] {subprocess.py:86} INFO - Output:
[2024-10-08T14:33:49.930+0000] {subprocess.py:93} INFO - Unable to find image 'kostasmitalloulis/sofascoe_scraper_image_up:latest' locally
[2024-10-08T14:33:51.558+0000] {subprocess.py:93} INFO - latest: Pulling from kostasmitalloulis/sofascoe_scraper_image_up
[2024-10-08T14:33:51.561+0000] {subprocess.py:93} INFO - ba83bbfca944: Already exists
[2024-10-08T14:33:51.576+0000] {subprocess.py:93} INFO - 48e779000ed2: Already exists
[2024-10-08T14:33:51.581+0000] {subprocess.py:93} INFO - 6d691dff6d17: Already exists
[2024-10-08T14:33:51.585+0000] {subprocess.py:93} INFO - 54cfd3060466: Already exists
[2024-10-08T14:33:51.591+0000] {subprocess.py:93} INFO - de88d2367fa4: Already exists
[2024-10-08T14:33:51.595+0000] {subprocess.py:93} INFO - 203a2ed516c5: Already exists
[2024-10-08T14:33:51.598+0000] {subprocess.py:93} INFO - 1098fe96b80e: Already exists
[2024-10-08T14:33:51.601+0000] {subprocess.py:93} INFO - cd8e006d5451: Already exists
[2024-10-08T14:33:51.607+0000] {subprocess.py:93} INFO - 7ad1e9b29e9f: Already exists
[2024-10-08T14:33:51.612+0000] {subprocess.py:93} INFO - 41837d337653: Already exists
[2024-10-08T14:33:51.616+0000] {subprocess.py:93} INFO - 9760b483e39f: Already exists
[2024-10-08T14:33:51.623+0000] {subprocess.py:93} INFO - c40a00e15ad1: Already exists
[2024-10-08T14:33:51.628+0000] {subprocess.py:93} INFO - 6b609d0d34f7: Already exists
[2024-10-08T14:33:51.633+0000] {subprocess.py:93} INFO - c909bc22699e: Already exists
[2024-10-08T14:33:51.639+0000] {subprocess.py:93} INFO - 399169395b2e: Already exists
[2024-10-08T14:33:51.643+0000] {subprocess.py:93} INFO - 030c072bb975: Already exists
[2024-10-08T14:33:51.647+0000] {subprocess.py:93} INFO - d7703c55093d: Already exists
[2024-10-08T14:33:51.650+0000] {subprocess.py:93} INFO - 2a1870666e16: Already exists
[2024-10-08T14:33:51.653+0000] {subprocess.py:93} INFO - 916865935dac: Already exists
[2024-10-08T14:33:52.007+0000] {subprocess.py:93} INFO - Digest: sha256:b006a03f459412ff1f832f038b08ce4a3c259b5f5216e68ba1f72d9e2656c479
[2024-10-08T14:33:52.010+0000] {subprocess.py:93} INFO - Status: Downloaded newer image for kostasmitalloulis/sofascoe_scraper_image_up:latest
[2024-10-08T14:33:52.112+0000] {subprocess.py:93} INFO - 7fdf27d543771f7b65ad694902b9af093e2005282b3a319ad14d8d6a23154031
[2024-10-08T14:33:52.779+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-08T14:33:52.780+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T14:33:52.818+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=update_database, task_id=run_sofascore_scraper, run_id=manual__2024-10-08T14:20:23.650666+00:00, execution_date=20241008T142023, start_date=20241008T143349, end_date=20241008T143352
[2024-10-08T14:33:52.878+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-08T14:33:52.904+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T14:33:52.905+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
