[2024-10-09T14:14:06.698+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-09T14:14:06.726+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_database.run_docker_container manual__2024-10-09T14:13:57.327900+00:00 [queued]>
[2024-10-09T14:14:06.738+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_database.run_docker_container manual__2024-10-09T14:13:57.327900+00:00 [queued]>
[2024-10-09T14:14:06.740+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-09T14:14:06.757+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_docker_container> on 2024-10-09 14:13:57.327900+00:00
[2024-10-09T14:14:06.768+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=543) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-09T14:14:06.774+0000] {standard_task_runner.py:63} INFO - Started process 545 to run task
[2024-10-09T14:14:06.774+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_database', 'run_docker_container', 'manual__2024-10-09T14:13:57.327900+00:00', '--job-id', '3876', '--raw', '--subdir', 'DAGS_FOLDER/update.py', '--cfg-path', '/tmp/tmpnmjccmu3']
[2024-10-09T14:14:06.775+0000] {standard_task_runner.py:91} INFO - Job 3876: Subtask run_docker_container
[2024-10-09T14:14:06.870+0000] {task_command.py:426} INFO - Running <TaskInstance: update_database.run_docker_container manual__2024-10-09T14:13:57.327900+00:00 [running]> on host 9ee81962cd27
[2024-10-09T14:14:07.013+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_database' AIRFLOW_CTX_TASK_ID='run_docker_container' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T14:13:57.327900+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-09T14:13:57.327900+00:00'
[2024-10-09T14:14:07.017+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-09T14:14:09.477+0000] {logging_mixin.py:188} INFO - Container 'sofascore_scraper_container' is running with DATE_ENV=None and bind mount C:/Users/efsta/Desktop/Kostas/Data/football_scotland/***/dags/sofascore_scraper_container/csv -> /app/csv
[2024-10-09T14:14:09.479+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-09T14:14:09.481+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-09T14:14:09.493+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=update_database, task_id=run_docker_container, run_id=manual__2024-10-09T14:13:57.327900+00:00, execution_date=20241009T141357, start_date=20241009T141406, end_date=20241009T141409
[2024-10-09T14:14:09.521+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-09T14:14:09.547+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-09T14:14:09.550+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
