[2024-10-09T12:47:34.365+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-09T12:47:34.406+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_database.test_postgres_connection manual__2024-10-09T12:47:29.288963+00:00 [queued]>
[2024-10-09T12:47:34.420+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_database.test_postgres_connection manual__2024-10-09T12:47:29.288963+00:00 [queued]>
[2024-10-09T12:47:34.422+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-09T12:47:34.444+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_postgres_connection> on 2024-10-09 12:47:29.288963+00:00
[2024-10-09T12:47:34.457+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-09T12:47:34.460+0000] {standard_task_runner.py:63} INFO - Started process 131 to run task
[2024-10-09T12:47:34.460+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_database', 'test_postgres_connection', 'manual__2024-10-09T12:47:29.288963+00:00', '--job-id', '3865', '--raw', '--subdir', 'DAGS_FOLDER/update.py', '--cfg-path', '/tmp/tmptlia8fn7']
[2024-10-09T12:47:34.461+0000] {standard_task_runner.py:91} INFO - Job 3865: Subtask test_postgres_connection
[2024-10-09T12:47:34.518+0000] {task_command.py:426} INFO - Running <TaskInstance: update_database.test_postgres_connection manual__2024-10-09T12:47:29.288963+00:00 [running]> on host e77972c4fa98
[2024-10-09T12:47:34.693+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_database' AIRFLOW_CTX_TASK_ID='test_postgres_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T12:47:29.288963+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-09T12:47:29.288963+00:00'
[2024-10-09T12:47:34.695+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-09T12:47:34.704+0000] {logging_mixin.py:188} INFO - Connection to PostgreSQL DB successful
[2024-10-09T12:47:34.710+0000] {logging_mixin.py:188} INFO - Data exported to /opt/***/dags/csvs/date_csv/last_date.csv successfully.
[2024-10-09T12:47:34.711+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-09T12:47:34.712+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-09T12:47:34.725+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=update_database, task_id=test_postgres_connection, run_id=manual__2024-10-09T12:47:29.288963+00:00, execution_date=20241009T124729, start_date=20241009T124734, end_date=20241009T124734
[2024-10-09T12:47:34.755+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-09T12:47:34.787+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-09T12:47:34.789+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
