[2024-10-08T15:40:09.500+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-08T15:40:09.521+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_database.test_postgres_connection manual__2024-10-08T15:40:05.537459+00:00 [queued]>
[2024-10-08T15:40:09.531+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_database.test_postgres_connection manual__2024-10-08T15:40:05.537459+00:00 [queued]>
[2024-10-08T15:40:09.532+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-08T15:40:09.545+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_postgres_connection> on 2024-10-08 15:40:05.537459+00:00
[2024-10-08T15:40:09.553+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1142) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T15:40:09.555+0000] {standard_task_runner.py:63} INFO - Started process 1144 to run task
[2024-10-08T15:40:09.554+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_database', 'test_postgres_connection', 'manual__2024-10-08T15:40:05.537459+00:00', '--job-id', '3848', '--raw', '--subdir', 'DAGS_FOLDER/update.py', '--cfg-path', '/tmp/tmpfa99la78']
[2024-10-08T15:40:09.555+0000] {standard_task_runner.py:91} INFO - Job 3848: Subtask test_postgres_connection
[2024-10-08T15:40:09.597+0000] {task_command.py:426} INFO - Running <TaskInstance: update_database.test_postgres_connection manual__2024-10-08T15:40:05.537459+00:00 [running]> on host 1fee8bc549a8
[2024-10-08T15:40:09.683+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_database' AIRFLOW_CTX_TASK_ID='test_postgres_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T15:40:05.537459+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T15:40:05.537459+00:00'
[2024-10-08T15:40:09.684+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-08T15:40:09.693+0000] {logging_mixin.py:188} INFO - (datetime.date(2024, 5, 19), datetime.time(15, 0), 'Ross County')
[2024-10-08T15:40:09.694+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-08T15:40:09.695+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T15:40:09.705+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=update_database, task_id=test_postgres_connection, run_id=manual__2024-10-08T15:40:05.537459+00:00, execution_date=20241008T154005, start_date=20241008T154009, end_date=20241008T154009
[2024-10-08T15:40:09.729+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-08T15:40:09.752+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-08T15:40:09.754+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
